name: PR:4.x

on:
  pull_request:
    branches:
      - 4.x

jobs:
  Ubuntu2004-ARM64:
    uses: davidmartos96/ci-gha-workflow/.github/workflows/OCV-PR-4.x-ARM64.yaml@main

  Ubuntu2004-ARM64-Debug:
    uses: davidmartos96/ci-gha-workflow/.github/workflows/OCV-PR-4.x-ARM64-Debug.yaml@main

  Ubuntu2004-x64:
    uses: davidmartos96/ci-gha-workflow/.github/workflows/OCV-PR-4.x-U20.yaml@main

  Ubuntu2004-x64-CUDA:
    if: "${{ contains(github.event.pull_request.labels.*.name, 'category: dnn') }} || ${{ contains(github.event.pull_request.labels.*.name, 'category: dnn (onnx)') }}"
    uses: davidmartos96/ci-gha-workflow/.github/workflows/OCV-PR-4.x-U20-Cuda.yaml@main

  Windows10-x64:
    uses: davidmartos96/ci-gha-workflow/.github/workflows/OCV-PR-4.x-W10.yaml@main

  macOS-ARM64:
    uses: davidmartos96/ci-gha-workflow/.github/workflows/OCV-PR-4.x-macOS-ARM64.yaml@main

  macOS-x64:
    uses: davidmartos96/ci-gha-workflow/.github/workflows/OCV-PR-4.x-macOS-x86_64.yaml@main

  iOS:
    uses: davidmartos96/ci-gha-workflow/.github/workflows/OCV-PR-4.x-iOS.yaml@main

  Android:
    uses: davidmartos96/ci-gha-workflow/.github/workflows/OCV-PR-4.x-Android.yaml@main

  TIM-VX:
    uses: davidmartos96/ci-gha-workflow/.github/workflows/OCV-timvx-backend-tests-4.x.yml@main

  docs:
    uses: davidmartos96/ci-gha-workflow/.github/workflows/OCV-PR-4.x-docs.yaml@main
